# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0esplitinference\"O\n\rTensorRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"f\n\x0bTensorReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x17\n\x0fpredicted_class\x18\x05 \x01(\t\"\x0f\n\rHealthRequest\"\x1d\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9b\x01\n\x0eSplitInference\x12\x43\n\x05Infer\x12\x1d.splitinference.TensorRequest\x1a\x1b.splitinference.TensorReply\x12\x44\n\x06Health\x12\x1d.splitinference.HealthRequest\x1a\x1b.splitinference.HealthReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORREQUEST']._serialized_start=35
  _globals['_TENSORREQUEST']._serialized_end=114
  _globals['_TENSORREPLY']._serialized_start=116
  _globals['_TENSORREPLY']._serialized_end=218
  _globals['_HEALTHREQUEST']._serialized_start=220
  _globals['_HEALTHREQUEST']._serialized_end=235
  _globals['_HEALTHREPLY']._serialized_start=237
  _globals['_HEALTHREPLY']._serialized_end=266
  _globals['_SPLITINFERENCE']._serialized_start=269
  _globals['_SPLITINFERENCE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
